# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Bili Download

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: download...
      run: |
        yutto https://www.bilibili.com/video/BV1MY41137AK -d ./download
      
    - name: 提交代码
      run: |
        git config --local user.email "dengrunsen@qq.com"
        git config --local user.name "Denrusn"
        git pull 
        git add .
        git commit -m "Update my server"
        
    - name: 推送
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      # run: |
      #   git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/Denrusn/schel.git
      #   git push -u origin main
