# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    - cron:  '5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run server
      run: |
        python server.py
    - name: Run a one-line script
      run: echo Helloooooooooooooooooooooooooooooo, world!
      
    - name: '打完收工,提交代码!'
      run: |
        git config --local user.email "1129159201@qq.com"
        git config --local user.name "rcy1314"
        git remote set-url origin https://${{ github.actor }}:${{ secrets.MYGG_TOKEN }}@github.com/${{ github.repository }}
        git pull 
        cp -Rf result.txt logs/${{env.TODAY_DATE}}.txt
        git add .
        git commit -m "Update By Github Action Bot"
        git push
